export { default as HomePage } from './home/home';
export { default as ProfilePage } from './profile/profile';
export { default as ControllerPage } from './controllers/controllers';
export { default as TriggerPage } from './triggers/triggers';
export { default as TriggerFormPage } from './triggers-form/triggers-form';
export { default as SensorsPage } from './sensors/sensors'
export { default as SensorDataPage } from './sensor-data/sensordata'
export { default as DevicePage } from './devices/devices'
export { default as CommandLogPage } from './commandlog/commandlog'
export { default as SensorFormPage } from './sensors-form/sensors-form'