export { default as HomePage } from './home/home';
export { default as ProfilePage } from './profile/profile';
export { default as ControllerPage } from './controllers/controllers';
export { default as TriggerPage } from './triggers/triggers';
export { default as TriggerFormPage } from './triggers-form/triggers-form';
export { default as SensorsPage } from './sensors/sensors'
export { default as SensorDataPage } from './sensor-data/sensordata'
export { default as DevicePage } from './devices/devices'
export { default as CommandLogPage } from './commandlog/commandlog'
export { default as SensorFormPage } from './sensors-form/sensors-form'
export { default as ShedulesPage } from './shedule/shedules'
export { default as ShedulesFormPage } from './shedule/shedules-form'
export { default as SheduleTasksPage } from './shedule-task/shedule-tasks'
export { default as SheduleTasksFormPage } from './shedule-task/shedule-task-form'
export { default as CommandsPage } from './command/commands'
export { default as CommandsFormPage } from './command/commands-form'
export { default as SheduleTaskGraphPage } from './shedule-task-graph/shedule-task-graph'